apiVersion: apps/v1
kind: Deployment
metadata:
  name: erica-backend-sample-app
  namespace: eri-dev-env
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend    
      containers:
        - name: eri-backend-app
          image: '__DOCKER_REPOSITORY__/__IMAGE_NAME__:__IMAGE_TAG__'
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: erica-backend-sample-app
  namespace: eri-dev-env
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
  type: LoadBalancer
  selector:
    app: web